// <auto-generated />
using EquipHostWebApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EquipHostWebApi.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241212145212_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EquipHostWebApi.Domain.Entities.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<string>("EquipmentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FacilityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ContractId");

                    b.HasIndex("EquipmentCode");

                    b.HasIndex("FacilityCode");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("EquipHostWebApi.Domain.Entities.EquipmentType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("EquipmentTypes");

                    b.HasData(
                        new
                        {
                            Code = "E001",
                            Area = 20.0,
                            Name = "Machine X"
                        },
                        new
                        {
                            Code = "E002",
                            Area = 15.0,
                            Name = "Machine Y"
                        });
                });

            modelBuilder.Entity("EquipHostWebApi.Domain.Entities.Facility", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("StandardArea")
                        .HasColumnType("float");

                    b.HasKey("Code");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            Code = "F001",
                            Name = "Factory A",
                            StandardArea = 500.0
                        },
                        new
                        {
                            Code = "F002",
                            Name = "Factory B",
                            StandardArea = 300.0
                        });
                });

            modelBuilder.Entity("EquipHostWebApi.Domain.Entities.Contract", b =>
                {
                    b.HasOne("EquipHostWebApi.Domain.Entities.EquipmentType", "EquipmentType")
                        .WithMany()
                        .HasForeignKey("EquipmentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquipHostWebApi.Domain.Entities.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentType");

                    b.Navigation("Facility");
                });
#pragma warning restore 612, 618
        }
    }
}
